# Tells Travis we're running on a Node environment
language: 'node_js'
node_js: '12'

# https://docs.travis-ci.com/user/caching/#yarn-cache
cache: yarn


# Script that is run before the script phase
#before_script:
#- yarn buildStorybook

build:
- echo "$NPM_TOKEN"
